src/config/routes.rb
Rails.application.routes.draw do
  # チャット
  get "chat/index"
  post "chat/store_ac"
  post "chat/store_redis"

  # ツイート
  get "tweets_js/index"
  resources :tweets

  # 管理画面
  scope "/admin_secret" do
    devise_for :admin_users, controllers: {
      sessions: 'admin_users/sessions',
      passwords: 'admin_users/passwords',
    }

    scope as: "admin", module: "admin" do
      get "", to: "home#index"
      resources :users, except: [:show]
    end
  end

  # ユーザー関連
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations',
    unlocks: 'users/unlocks',
    #omniauth_callbacks: "users/omniauth_callbacks"
  }

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "home#index"

  # 開発者向けページ
  get "development/index"
  get "development/ruby_test"
  get "development/view_test"
  post "development/view_test_post"
  get "development/javascript_test"
  post "api/development/go_api_test"
  get "development/websocket_test"
end

src/app/controllers/api/development_controller.rb
# 開発者向けページ
class Api::DevelopmentController < Api::ApplicationController
  # CSRF チェックを無効化
  #skip_before_action :verify_authenticity_token, only: [:go_api_test]

  # GOからのレスポンステスト
  def go_api_test
    jwt_token_service = WebsocketServices::JwtTokenService.new

    token = jwt_token_service.get_jwt(request)
    ret = jwt_token_service.parse_jwt(token)

    p("parse result", ret)

    if ret
      p('valid token')
      user_id = ret[:user_id]
      user = User.find(user_id)
      p("user", user)

      p("params[:title]", params[:title])
      p("params[:sender_message]", params[:sender_message])

      render json: { status: 'OK' }
      return
    else
      p('invalid token')
      render json: { status: 'NG', error: 'Unauthorized' }, status: :unauthorized
      return
    end
  end
end

src/app/controllers/development_controller.rb
# 開発者向けページ
class DevelopmentController < ApplicationController
  def index
  end

  # Ruby動作確認
  def ruby_test
    sample_service = SampleServices::SampleService.new
    sample_service.test_exec("ruby_test")

    user = current_user

    p('user', user)
    p('user.to_json', user.to_json)
    p('user.as_json', user.as_json)
    p('user.as_json(include: :user_tweets)', user.as_json(include: :user_tweets))

    tweet = user.user_tweets.first

    if tweet
      p('tweet', tweet)
      p('tweet.to_json(include: :user)', tweet.to_json(include: :user))
      p('tweet.as_json(include: :user)', tweet.as_json(include: :user))
    end

    memory_mb = `ps -o rss= -p #{Process.pid}`.to_i / 1024.0
    Rails.logger.info "使用メモリ: #{memory_mb.round(2)} MB"

    render :complate
  end

  # View動作確認
  def view_test
    view_test_common
    @form = ViewTestForm.new
    @form.list_val = 2
    @form.radio_val = "val1"
    @form.datetime_val = "2026-02-15T14:30"
  end
  def view_test_post
    view_test_common
    @form = ViewTestForm.new

    @form.assign_attributes(view_test_params)

    render :view_test
  end
  private def view_test_common
    @list_vals = {
      1 => "No. 1",
      2 => "No. 2",
      3 => "No. 3"
    }
    @radio_vals = {
      "val1" => "Value 1",
      "val2" => "Value 2"
    }
  end
  private def view_test_params
    params.expect(view_test_form: [ :list_val, :radio_val, :datetime_val ])
  end

  # Javascript動作確認
  def javascript_test
    @name = "Test!!"
  end
end

src/app/helpers/development_helper.rb
module DevelopmentHelper
end

src/app/views/development/complate.html.erb
実行しました。

src/app/views/development/frontend_test.html.erb
<%= vite_typescript_tag 'development' %>

<div id="react-root" data-all="<%= {
  name: @name
}.to_json %>">
  <%= render 'shared/message/loading' %>
</div>

<div id="vue-root" data-all="<%= {
  name: @name
}.to_json %>">
  <%= render 'shared/message/loading' %>
</div>

<div class="my-6 text-lg">読み込み中表示の動作確認</div>
<div class="mt-5 border-gray-500 border-2 p-0">
  <%= render 'shared/message/loading' %>
</div>
<div class="mt-5 border-gray-500 border-2 p-0">
  <%= render 'shared/message/loading' %>
</div>

src/app/views/development/index.html.erb
<p><%= link_to "ruby_test", development_ruby_test_path, class: "app-link-normal" %></p>
<p><%= link_to "view_test", development_view_test_path, class: "app-link-normal" %></p>
<p><%= link_to "javascript_test", development_javascript_test_path, class: "app-link-normal" %></p>

src/app/views/development/javascript_test.html.erb
<%= vite_typescript_tag 'development' %>

<div id="react-root" data-all="<%= {
  name: @name
}.to_json %>">
  <%= render 'shared/message/loading' %>
</div>

<div id="vue-root" data-all="<%= {
  name: @name
}.to_json %>">
  <%= render 'shared/message/loading' %>
</div>

<div class="my-6 text-lg">読み込み中表示の動作確認</div>
<div class="mt-5 border-gray-500 border-2 p-0">
  <%= render 'shared/message/loading' %>
</div>
<div class="mt-5 border-gray-500 border-2 p-0">
  <%= render 'shared/message/loading' %>
</div>

src/app/views/development/react_test.html.erb
<%= vite_typescript_tag 'development' %>

<div id="test-container" data-all="<%= {
  name: @name
}.to_json %>"></div>

src/app/views/development/view_test.html.erb
<%= form_with model: @form, url: development_view_test_post_path do |f| %>

  <div class="mt-5">
    <%= f.label :list_val, "リスト動作確認" %>
    <%= f.select :list_val, @list_vals.map { |k, v| [v, k] }, { prompt: "選択してください" } %>
  </div>

  <div class="mt-5">
    <%= f.label :list_val, "ラジオボタン動作確認" %>
    <% @radio_vals.each do |key, value| %>
      <%= f.label :"radio_val_#{key}" do %>
        <%= f.radio_button :radio_val, key %>
        <%= value %>
      <% end %>
    <% end %>
  </div>

  <div class="mt-5">
    <%= f.label :datetime_val, "日時動作確認" %>
    <%= f.datetime_local_field :datetime_val, class: "app-form-input w-auto" %>
  </div>

  <div class="mt-5">
    <%= f.submit "送信", class: "app-btn-primary" %>
  </div>

<% end %>